### ISSUE TITLE
Поддержка порядка колонок внутри борда и историй внутри колонки

### ISSUE THREAD

**Issue by zharinov** [friezze-dev/friezze-go#3]
Сейчас перетаскивание в лучшем случае работает только на фронтенде.
Хочется уметь его читать и записывать.
По умолчанию, в случае отсутствия информации, клиент применит каноническую сортировку.

**Comment by alwx** [comment]
Наверное, самый простой и эффективный вариант, который приходит в голову — добавить к объекту колонки поле story_order и хранить там список вроде `[<story_uuid_1>, <story_uuid_2>, <story_uuid_3>, ...]`. В таком случае фронтенд будет получать все задачи, а потом менять их порядок в зависимости от того, что задано в story_order. 
Таким образом, при модификации порядка нам просто нужно будет делать `PATCH /boards/<board_id>` и передавать новый `story_order`.

Наверное, можно придумать и более эффективные способы (особенно по части записи), но мне кажется, что это ни к чему в данном случае.

@zharinov Что скажешь?
